### ISSUE TITLE
Difference between using kwargs or settings override to specify soccer settings

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/ev3sim#124]
Have two different ways of doing very similar functionality. The settings override is more general and should probably be kept for that reason, but is not a full superset of the functionality offered by specifying kwargs.

**Comment by glipR** [comment]
`kwargs` does have its uses, in cases where interactors are not singleton classes. Otherwise I agree we should use settings for the soccer and rescue settings now, since there will always only be one of them active.
