### ISSUE TITLE
Tick rate adjustments

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/ev3sim#132]
Adjust GAME_TICK_RATE, VISUAL_TICK_RATE, TIME_SCALE defaults in ScriptLoader (some 30 and some 60) and in soccer.yaml preset (both 30).

Move from loader to use settings (or is this not possible because not a singleton class?)

Add corresponding documentation including for TIME_SCALE

**Comment by glipR** [comment]
Oh I didn't even think about the loader settings, yeah good call.
