### ISSUE TITLE
Reorganise example code and yaml files

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/ev3sim#140]
https://github.com/MelbourneHighSchoolRobotics/ev3sim/tree/main/ev3sim/robots/scripts

Not a hard change, but need to update all locations that link here - including potentially outside this repository.

**Comment by peter-drew** [comment]
@glipR would this affect where ev3sim looks for default scripts?

**Comment by peter-drew** [comment]
Actually might be better off creating a new 'examples' folder and moving the robots, scripts and batched_command folders into it. But will require more link updates and probably code changes for the default search locations.

**Comment by glipR** [comment]
At the moment that would break stuff but its an easy fix.

**Comment by glipR** [comment]
I'd probably rather having a few bots in separate folders with bot yamls and python code, with batched commands one level up.

**Comment by glipR** [comment]
With the new gui and how that all works, We shouldn't need to delve into the package files really at all, especially from a student's perspective. I still agree this stuff should all sit in an examples folder though.

**Comment by glipR** [comment]
Fixed by #184
