### ISSUE TITLE
Add update available web check

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/ev3sim#150]
A system to alert the user on startup if an update is available.

Pretty simple to implement using requests. But means the application would need to access the internet. Thoughts?

**Comment by glipR** [comment]
We could just try and silently fail with no net. I'm happy with this, it should be more than a print, like an alert in pygame, if thats possible. Otherwise we could change the window title to include UPDATE AVAILABLE.
