### ISSUE TITLE
Controllable bot example fails

### ISSUE THREAD

**Issue by OwenFeik** [MelbourneHighSchoolRobotics/ev3sim#161]
When running `ev3sim controllable.yaml` the simulator errors and exits.

This occurs because the `ControllableBot` class calls `self.compass.calibrate()` in `.onSpawn()` before it has initialised it in `.startUp()`.

This could be resolved by moving the calibration from `onSpawn()` to `startUp()`.

**Comment by glipR** [comment]
Closed by #162
