### ISSUE TITLE
Mac / Linux v2 support

### ISSUE THREAD

**Issue by glipR** [MelbourneHighSchoolRobotics/ev3sim#218]
Hasn't been tested to any amount and I know mac currently doesn't work.

**Comment by glipR** [comment]
Edit: I think we might have Mac Support if Tkinter is installed with python?

**Comment by peter-drew** [comment]
@glipR does Mac not work even when installed through PIP?

**Comment by glipR** [comment]
Had a student try with mac and not working. I think its just the workspace select button (The very first thing) that breaks :D because it tries to open a file dialog.

**Comment by peter-drew** [comment]
Hopefully the addition of sentry will help diagnose that.
