### ISSUE TITLE
Notify robots that goal scored/ game reset

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/ev3sim#84]

**Comment by peter-drew** [comment]
If buttons were implemented (see #88) then could provide a way to bind events to button presses in the yaml file for each robot.

**Comment by peter-drew** [comment]
As noted in #89, the original reason for this issue was to automate simulations. If that is the desired outcome something more holistic is probably ideal. But this could still be useful in its own right.

**Comment by glipR** [comment]
I think what might be the most modular (and similar to the button API) would be a SimEvents singleton class in the helpers. You then redefine the events `on_score` and `on_reset` and they get called by the sim as things occur.

**Comment by glipR** [comment]
Closing since resolved by #95
