### ISSUE TITLE
Colour sensor raw mode behaviour

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/ev3sim#90]
The difference between RAW and RGB_RAW is more than just calibration in ev3dev2 - which LEDs are turned on changes.

**Comment by glipR** [comment]
Basing this comment off the modes here: https://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/stable/sensors.html#color-sensor

REF_RAW is reflected light intensity - something not yet implemented. At the moment we technically only implement the RGB_RAW mode, hence the only difference being bias/calibration.

What do you think would be a good estimation of Reflected Intensity based on rgb values?
